package io.github.koltalabs.kolt.composekmp.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import io.github.koltalabs.kolt.composekmp.wrappers.toUiDimen

// Platforms without density-qualified resources (desktop, iOS, wasmJs) use these literal dp/sp
// values, which mirror androidMain/res/values/dimens.xml. Android resolves the same numbers from
// resources instead. Without them, Sizes()/UiSizes() are all Dp/TextUnit.Unspecified: text has no
// size, and a widget that reads an un-overridden padding (e.g. KoltTextButton's contentPadding)
// feeds NaN into Modifier.padding and crashes with "Padding must be non-negative".

internal fun defaultSizes(): Sizes = Sizes(
    appBarSize = 56.dp,

    iconXSmall = 8.dp,
    iconSmall = 16.dp,
    iconMedium = 20.dp,
    iconStandard = 24.dp,
    iconStandardLarge = 28.dp,
    iconLarge = 32.dp,
    iconXLarge = 40.dp,
    iconXXLarge = 48.dp,
    iconXXXLarge = 56.dp,
    iconXXXXLarge = 64.dp,
    iconBig = 80.dp,
    iconGiant = 128.dp,

    paddingGiant = 56.dp,
    paddingXXXXLarge = 48.dp,
    paddingXXXLarge = 40.dp,
    paddingXXLarge = 32.dp,
    paddingXLarge = 24.dp,
    paddingLarge = 20.dp,
    paddingMedium = 16.dp,
    paddingSmallMedium = 12.dp,
    paddingSmall = 8.dp,
    paddingXSmallPlus = 6.dp,
    paddingXSmall = 4.dp,
    paddingXXSmall = 2.dp,
    paddingTiny = 1.dp,
    noPadding = 0.dp,

    cornerRadiusSmall = 3.dp,
    cornerRadiusMedium = 4.dp,
    cornerRadiusNormal = 8.dp,
    cornerRadiusMediumLarge = 12.dp,
    cornerRadiusLarge = 16.dp,
    cornerRadiusXLarge = 20.dp,
    cornerRadiusXXLarge = 24.dp,
    cornerRadiusXXXLarge = 32.dp,

    actionButtonSize = 48.dp,
    floatingButtonSizeSmall = 40.dp,
    floatingButtonSize = 48.dp,
    floatingButtonSizeLarge = 56.dp,

    fontSizeMinimum = 6.sp,
    fontSizeTiny = 7.sp,
    fontSizeXXXSmall = 8.sp,
    fontSizeXXSmall = 9.sp,
    fontSizeXSmall = 10.sp,
    fontSizeXSmallMedium = 11.sp,
    fontSizeSmall = 12.sp,
    fontSizeSmallMedium = 13.sp,
    fontSizeMedium = 14.sp,
    fontSizeMediumMid = 15.sp,
    fontSizeMediumLarge = 16.sp,
    fontSizeLarge = 18.sp,
    fontSizeXLarge = 20.sp,
    fontSizeXXLarge = 24.sp,
    fontSizeXXXLarge = 28.sp,
    fontSizeBig = 32.sp,
    fontSizeXBig = 36.sp,
    fontSizeHuge = 40.sp,
    fontSizeGiant = 48.sp,
    fontSizeMediumLargeMid = 17.sp,
    fontSizeXLargeMid = 22.sp,
    sizeXXXSmall = 8.dp,
    sizeXXSmall = 16.dp,
    sizeXSmall = 24.dp,
    sizeSmall = 32.dp,
    sizeSmallMedium = 36.dp,
    sizeMedium = 40.dp,
    sizeMediumLarge = 48.dp,
    sizeLarge = 56.dp,
    sizeXLarge = 64.dp,
    sizeXXLarge = 80.dp,
    sizeXXXLarge = 96.dp,
    sizeGiant = 128.dp,
    imageXXSmall = 24.dp,
    imageXSmall = 32.dp,
    imageSmall = 40.dp,
    imageSmallMedium = 48.dp,
    imageMedium = 64.dp,
    imageMediumLarge = 80.dp,
    imageLarge = 96.dp,
    imageXLarge = 120.dp,
    imageXXLarge = 160.dp,
    imageXXXLarge = 200.dp,
    imageHuge = 240.dp,
    imageGiant = 320.dp,
    imageSmallMediumPlus = 56.dp,
)

internal fun defaultUiSizes(): UiSizes = UiSizes(
    appBarSize = 56.dp.toUiDimen(),

    iconXSmall = 8.dp.toUiDimen(),
    iconSmall = 16.dp.toUiDimen(),
    iconMedium = 20.dp.toUiDimen(),
    iconStandard = 24.dp.toUiDimen(),
    iconStandardLarge = 28.dp.toUiDimen(),
    iconLarge = 32.dp.toUiDimen(),
    iconXLarge = 40.dp.toUiDimen(),
    iconXXLarge = 48.dp.toUiDimen(),
    iconXXXLarge = 56.dp.toUiDimen(),
    iconXXXXLarge = 64.dp.toUiDimen(),
    iconBig = 80.dp.toUiDimen(),
    iconGiant = 128.dp.toUiDimen(),

    paddingGiant = 56.dp.toUiDimen(),
    paddingXXXXLarge = 48.dp.toUiDimen(),
    paddingXXXLarge = 40.dp.toUiDimen(),
    paddingXXLarge = 32.dp.toUiDimen(),
    paddingXLarge = 24.dp.toUiDimen(),
    paddingLarge = 20.dp.toUiDimen(),
    paddingMedium = 16.dp.toUiDimen(),
    paddingSmallMedium = 12.dp.toUiDimen(),
    paddingSmall = 8.dp.toUiDimen(),
    paddingXSmallPlus = 6.dp.toUiDimen(),
    paddingXSmall = 4.dp.toUiDimen(),
    paddingXXSmall = 2.dp.toUiDimen(),
    paddingTiny = 1.dp.toUiDimen(),
    noPadding = 0.dp.toUiDimen(),

    cornerRadiusSmall = 3.dp.toUiDimen(),
    cornerRadiusMedium = 4.dp.toUiDimen(),
    cornerRadiusNormal = 8.dp.toUiDimen(),
    cornerRadiusMediumLarge = 12.dp.toUiDimen(),
    cornerRadiusLarge = 16.dp.toUiDimen(),
    cornerRadiusXLarge = 20.dp.toUiDimen(),
    cornerRadiusXXLarge = 24.dp.toUiDimen(),
    cornerRadiusXXXLarge = 32.dp.toUiDimen(),

    actionButtonSize = 48.dp.toUiDimen(),
    floatingButtonSizeSmall = 40.dp.toUiDimen(),
    floatingButtonSize = 48.dp.toUiDimen(),
    floatingButtonSizeLarge = 56.dp.toUiDimen(),

    fontSizeMinimum = 6.sp.toUiDimen(),
    fontSizeTiny = 7.sp.toUiDimen(),
    fontSizeXXXSmall = 8.sp.toUiDimen(),
    fontSizeXXSmall = 9.sp.toUiDimen(),
    fontSizeXSmall = 10.sp.toUiDimen(),
    fontSizeXSmallMedium = 11.sp.toUiDimen(),
    fontSizeSmall = 12.sp.toUiDimen(),
    fontSizeSmallMedium = 13.sp.toUiDimen(),
    fontSizeMedium = 14.sp.toUiDimen(),
    fontSizeMediumMid = 15.sp.toUiDimen(),
    fontSizeMediumLarge = 16.sp.toUiDimen(),
    fontSizeLarge = 18.sp.toUiDimen(),
    fontSizeXLarge = 20.sp.toUiDimen(),
    fontSizeXXLarge = 24.sp.toUiDimen(),
    fontSizeXXXLarge = 28.sp.toUiDimen(),
    fontSizeBig = 32.sp.toUiDimen(),
    fontSizeHuge = 40.sp.toUiDimen(),
    fontSizeGiant = 48.sp.toUiDimen(),
    fontSizeMediumLargeMid = 17.sp.toUiDimen(),
    fontSizeXLargeMid = 22.sp.toUiDimen(),
    fontSizeXBig = 36.sp.toUiDimen(),
    sizeXXXSmall = 8.dp.toUiDimen(),
    sizeXXSmall = 16.dp.toUiDimen(),
    sizeXSmall = 24.dp.toUiDimen(),
    sizeSmall = 32.dp.toUiDimen(),
    sizeSmallMedium = 36.dp.toUiDimen(),
    sizeMedium = 40.dp.toUiDimen(),
    sizeMediumLarge = 48.dp.toUiDimen(),
    sizeLarge = 56.dp.toUiDimen(),
    sizeXLarge = 64.dp.toUiDimen(),
    sizeXXLarge = 80.dp.toUiDimen(),
    sizeXXXLarge = 96.dp.toUiDimen(),
    sizeGiant = 128.dp.toUiDimen(),
    imageXXSmall = 24.dp.toUiDimen(),
    imageXSmall = 32.dp.toUiDimen(),
    imageSmall = 40.dp.toUiDimen(),
    imageSmallMedium = 48.dp.toUiDimen(),
    imageMedium = 64.dp.toUiDimen(),
    imageMediumLarge = 80.dp.toUiDimen(),
    imageLarge = 96.dp.toUiDimen(),
    imageXLarge = 120.dp.toUiDimen(),
    imageXXLarge = 160.dp.toUiDimen(),
    imageXXXLarge = 200.dp.toUiDimen(),
    imageHuge = 240.dp.toUiDimen(),
    imageGiant = 320.dp.toUiDimen(),
    imageSmallMediumPlus = 56.dp.toUiDimen(),
)
